---

- hosts: all
  connection: local
  gather_facts: no

  vars_prompt:
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"

        password: "{{ mgmt_password }}"

  - name: IOS | show clock
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show clock
    register: clock

  - debug: msg="{{ clock.stdout }}"

  - name: store to file
    template: src=~/ansible/test/integration/targets/ios_config/templates/defaults/config.j2 dest=data/{{ inventory_hostname }}_gather_data.json

