- hosts: all
  connection: local
  gather_facts: no

  vars_prompt:
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"

        password: "{{ mgmt_password }}"

  - name: IOS | Term len 0
    ios_command:
      provider: "{{ provider }}"
      commands:
        - term len 0
    
  - name: IOS | show version
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show version
    register: version

  - debug: msg="{{ version.stdout }}"

  - name: IOS | show inventory
    ios_command:
      provider: "{{ provider }}"
      commands: 
        - show inventory
    register: inventory

  - debug: msg="{{ inventory.stdout }}"

#  - name: IOS | show run
#    ios_command:
#      provider: "{{ provider }}"
#      commands:
#        - show run
#    register: run

#  - debug: msg="{{ run.stdout }}"
 
  - name: IOS | show interface status
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show interface status
    register: int_status

  - debug: msg="{{ int_status.stdout }}"

  - name: IOS | show cdp neigh
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show cdp neighbor
    register: cdp_n

  - debug: msg="{{ cdp_n.stdout }}"

  - name: IOS | show ip arp
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show ip arp
    register: ip_arp

  - debug: msg="{{ ip_arp.stdout }}"

  - name: IOS | show ip route
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show ip route
    register: ip_route_tbl

  - debug: msg="{{ ip_route_tbl.stdout }}"

  - name: IOS | show ip protocols
    ios_command:
      provider: "{{ provider }}"
      commands:
        - show ip protocols
    register: ip_protocols

  - debug: msg="{{ ip_protocols.stdout }}"

